# Generated by Django 4.2.16 on 2024-10-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('encontrado', 'Encontrado')], default='pendente', max_length=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('ocorrencias', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
